// Generated by dia2code
#ifndef STATE__CHARACTERSTATUSID__H
#define STATE__CHARACTERSTATUSID__H


namespace state {

  enum CharacterStatusID {
    PLAYING     = 1,
    WAITING     = 2,
    DEATH     = 3,
    WIN     = 4,
    WANDER     = 5
  };

};

#endif
