// Generated by dia2code
#ifndef STATE__CHARACTERSTATUSID__H
#define STATE__CHARACTERSTATUSID__H


namespace state {

  enum CharacterStatusID {
    FIGHTING     = 1,
    WAITING     = 2,
    DEAD     = 3,
    WIN     = 4,
    WANDERING     = 5
  };

};

#endif
