// Generated by dia2code
#ifndef STATE__CHARACTER__H
#define STATE__CHARACTER__H


namespace state {
  class Stats;
  class Spells;
  class Element;
}

#include "Stats.h"
#include "Spells.h"
#include "Element.h"
#include "TypeID.h"
#include "MobTypeID.h"
#include "CharacterStatusID.h"

namespace state {

  /// class Character - 
  class Character : public state::Element {
    // Associations
    // Attributes
  protected:
     typeID;
    Stats stats;
    playerTypeID typeID;
    playerStatusID status;
    Spells spells;
     characterID;
    // Operations
  public:
    Stats& getStats ();
    Spells& getSpells ();
    PlayerTypeID getType ();
    LevelUp ();
    // Setters and Getters
    const & getTypeID() const;
    void setTypeID(const & typeID);
    void setStats(const Stats& stats);
    const playerTypeID& getTypeID() const;
    void setTypeID(const playerTypeID& typeID);
    const playerStatusID& getStatus() const;
    void setStatus(const playerStatusID& status);
    void setSpells(const Spells& spells);
    const & getCharacterID() const;
    void setCharacterID(const & characterID);
  };

};

#endif
