// Generated by dia2code
#ifndef STATE__CURSOR__H
#define STATE__CURSOR__H


namespace state {
  class Position;
  class Element;
}

#include "Element.h"

namespace state {

  /// class Cursor - 
  class Cursor : public state::Element {
    // Operations
  public:
    Cursor (int x = 0, int y = 0);
    bool isMapCell ();
    void move (Position& destination);
    // Setters and Getters
  };

};

#endif
