// Generated by dia2code
#ifndef STATE__DAMAGEID__H
#define STATE__DAMAGEID__H


namespace state {

  enum DamageID {
    PUNCH_DMG     = 3,
    THROW_DMG     = 2,
    IGNITE_DMG     = 1
  };

};

#endif
