// Generated by dia2code
#ifndef STATE__DAMAGEID__H
#define STATE__DAMAGEID__H


namespace state {

  enum DamageID {
    PUNCH_DMG     = 30,
    THROW_DMG     = 20,
    IGNITE_DMG     = 25
  };

};

#endif
