// Generated by dia2code
#ifndef STATE__ELEMENT__H
#define STATE__ELEMENT__H

#include <string>

namespace state {
  class Position;
}

#include "Position.h"

namespace state {

  /// class Element - 
  class Element {
    // Associations
    // Attributes
  public:
    std::string name;
    Position position;
    /// On va pas forcément l'utiliser, mais on le garde au cas où
    int tileCode;
    // Operations
  public:
    Element ();
    bool isMapCell ();
    Position getPosition ();
    /// Le getter et setterde tile pas forcément utile mais on les garde quand meme au cas où
    int getTileCode ();
    /// Le getter et setterde tile pas forcément utile mais on les garde quand meme au cas où
    /// @param eltTileCode		(???) 
    void setTileCode (int eltTileCode);
    // Setters and Getters
  };

};

#endif
