// Generated by dia2code
#ifndef STATE__ELEMENT__H
#define STATE__ELEMENT__H

#include <string>

namespace state {
  class Position;
}

#include "Position.h"

namespace state {

  /// class Element - 
  class Element {
    // Associations
    // Attributes
  public:
    std::string name;
    Position position;
    // Operations
  public:
    Element ();
    bool isMapCell ();
    Position getPosition ();
    // Setters and Getters
  };

};

#endif
