// Generated by dia2code
#ifndef STATE__FIGHT__H
#define STATE__FIGHT__H


namespace state {
  class State;
}

#include "StateFightAction.h"
#include "State.h"

namespace state {

  /// class Fight - 
  class Fight : public state::State {
    // Associations
    // Attributes
  public:
    int turn     = 0;
    bool end;
    bool win;
    bool loose;
    // Operations
  public:
    int getTurn ();
    int getEnd ();
    void setTurn (int newTurn);
    void setEnd (bool res);
    int getFightAction (StateFightAction state);
    // Setters and Getters
  };

};

#endif
