// Generated by dia2code
#ifndef STATE__FIGHT__H
#define STATE__FIGHT__H


namespace state {
  class State;
}

#include "StateFightAction.h"
#include "State.h"

namespace state {

  /// class Fight - 
  class Fight : public state::State {
    // Associations
    // Attributes
  public:
    int currentTurn     = 0;
    bool end;
    bool win;
    StateFightAction currentFightAction;
    // Operations
  public:
    int getCurrentTurn ();
    int getEnd ();
    void setCurrentTurn (int newTurn);
    void setEnd (bool res);
    StateFightAction getFightAction ();
    void setFightAction (StateFightAction newStateFightAction);
    void setWin (bool sbwon);
    // Setters and Getters
  };

};

#endif
