// Generated by dia2code
#ifndef STATE__MAPCELL__H
#define STATE__MAPCELL__H


namespace state {
  class Element;
}

#include "Element.h"

namespace state {

  /// class MapCell - 
  class MapCell : public state::Element {
    // Operations
  public:
    bool isOccupied ();
    // Setters and Getters
  };

};

#endif
