// Generated by dia2code
#ifndef STATE__OBSERVABLE__H
#define STATE__OBSERVABLE__H

#include <vector>

namespace state {
  class IObserver;
}

#include "IObserver.h"

namespace state {

  /// class Observable - 
  class Observable {
    // Attributes
  private:
    std::vector<IObserver*> observers;
    // Operations
  public:
    void registerObserver (IObserver o);
    void notifyObservers ();
    void unregisterObserver (IObserver o);
    // Setters and Getters
  };

};

#endif
