// Generated by dia2code
#ifndef STATE__OBSTACLECELLID__H
#define STATE__OBSTACLECELLID__H


namespace state {

  enum ObstacleCellID {
    TREE     = 1,
    STUMP     = 2,
    WALLS     = 3,
    WATER     = 4
  };

};

#endif
