// Generated by dia2code
#ifndef STATE__OBSTACLECELL__H
#define STATE__OBSTACLECELL__H


namespace state {
  class MapCell;
}

#include "ObstacleCellID.h"
#include "MapCell.h"

namespace state {

  /// class ObstacleCell - 
  class ObstacleCell : public state::MapCell {
    // Associations
    // Attributes
  protected:
    ObstacleCellID typeID;
    // Operations
  public:
    ObstacleCell (ObstacleCellID id);
    ObstacleCellID getObstacleCellID ();
    // Setters and Getters
    ObstacleCellID getTypeID() const;
    void setTypeID(ObstacleCellID typeID);
  };

};

#endif
