// Generated by dia2code
#ifndef STATE__POSITION__H
#define STATE__POSITION__H


namespace state {

  /// class Position - 
  class Position {
    // Attributes
  public:
    int x;
    int y;
    // Operations
  public:
    Position (int x, int y);
    int getX ();
    int getY ();
    void setX (int nX);
    void setY (int nY);
    distance ();
    nearPositions ();
    // Setters and Getters
  };

};

#endif
