// Generated by dia2code
#ifndef STATE__POSITION__H
#define STATE__POSITION__H

#include <array>

namespace state {
  class Position;
}

namespace state {

  /// class Position - 
  class Position {
    // Attributes
  public:
    int x;
    int y;
    // Operations
  public:
    Position (int x, int y);
    int getX ();
    int getY ();
    void setX (int nX);
    void setY (int nY);
    int distance (Position& position1, Position& position2);
    std::array<std::array<int,30>,30> nearPositions (int x, int y);
    // Setters and Getters
  };

};

#endif
