// Generated by dia2code
#ifndef STATE__SPELLS__H
#define STATE__SPELLS__H


#include "SpellID.h"
#include "DamageID.h"
#include "RangeID.h"
#include "CostID.h"

namespace state {

  /// class Spells - 
  class Spells {
    // Associations
    // Attributes
  private:
    /// 	
    SpellID ID;
    DamageID Damage;
    RangeID Range;
    CostID Cost;
    // Operations
  public:
    int getID ();
    int getDamage ();
    int getCost ();
    int getRange ();
    // Setters and Getters
  };

};

#endif
