// Generated by dia2code
#ifndef STATE__SPELLS__H
#define STATE__SPELLS__H


#include "SpellID.h"
#include "DamageID.h"
#include "RangeID.h"
#include "CostID.h"

namespace state {

  /// class Spells - 
  class Spells {
    // Associations
    // Attributes
  private:
    /// 	
    SpellID ID;
    DamageID Damage;
    RangeID Range;
    CostID Cost;
    // Operations
  public:
    /// Normal pas de setteur, mais on fait lautre méthode ou instanciait les damage, ... manuellement on aurait eu besoin des setteurs comme pour les stats 
    /// @param id		(???) 
    /// @param damage		(???) 
    /// @param cost		(???) 
    /// @param range		(???) 
    Spells (SpellID id, DamageID damage, CostID cost, RangeID range);
    int getID ();
    int getDamage ();
    int getCost ();
    int getRange ();
    // Setters and Getters
  };

};

#endif
