// Generated by dia2code
#ifndef STATE__SPELLS__H
#define STATE__SPELLS__H


namespace state {

  /// class Spells - 
  class Spells {
    // Attributes
  private:
    /// 	
    int  ID;
    int Damage;
    int Range;
    int Cost;
    // Operations
  public:
    int getID ();
    int getDamage ();
    int getCost ();
    int getRange ();
    // Setters and Getters
  };

};

#endif
