// Generated by dia2code
#ifndef STATE__STATS__H
#define STATE__STATS__H


namespace state {

  /// class Stats - 
  class Stats {
    // Attributes
  private:
    int health;
    int actPoints;
    int movPoints;
    int experience;
    int level;
    // Operations
  public:
    int getHealth ();
    int getActPoints ();
    /// 				
    int getMovPoints ();
    int getExperience ();
    int getLevel ();
    void setHealth ();
    void setActPoints  ();
    void setMovPoints ();
    void setExperience ();
    void setLevel ();
    // Setters and Getters
  };

};

#endif
