// Generated by dia2code
#ifndef STATE__STATEFIGHTACTION__H
#define STATE__STATEFIGHTACTION__H


namespace state {

  enum StateFightAction {
    F_IDLE     = 1,
    F_MOVING     = 2,
    ATTACKING     = 3
  };

};

#endif
