// Generated by dia2code
#ifndef STATE__STATEWANDERACTION__H
#define STATE__STATEWANDERACTION__H


namespace state {

  enum StateWanderAction {
    W_IDLE     = 1,
    W_MOVING     = 2,
    LAUNCHING     = 3
  };

};

#endif
