// Generated by dia2code
#ifndef STATE__STATE__H
#define STATE__STATE__H

#include <array>
#include <vector>

namespace state {
  class Character;
  class Cursor;
  class Observable;
  class MapCell;
}

#include "Character.h"
#include "Cursor.h"
#include "Observable.h"
#include "MapCell.h"

namespace state {

  /// class State - 
  class State : public state::Observable {
    // Associations
    // Attributes
  private:
    std::array<std::array<int,30>,30> map;
    std::vector<Character> Characters;
    Cursor cursor;
    // Operations
  public:
    State ();
    std::vector<Character&> getCharacters ();
    void initializeCharacters ();
    void initializeMapCell ();
    Cursor& getCursor ();
    // Setters and Getters
  };

};

#endif
