// Generated by dia2code
#ifndef STATE__STATS__H
#define STATE__STATS__H


namespace state {

  /// class Stats - 
  class Stats {
    // Attributes
  public:
    int health;
    int actPoints;
    int movPoints;
    int experience;
    int level;
    // Operations
  public:
    int getHealth ();
    int getActPoints ();
    /// 				
    int getMovPoints ();
    int getExperience ();
    int getLevel ();
    void setHealth (int nHealth);
    void setActPoints  (int nAct);
    void setMovPoints (int nMov);
    void setExperience (int nExp);
    void setLevel (int nLev);
    // Setters and Getters
  };

};

#endif
