// Generated by dia2code
#ifndef STATE__STATEFIGHTACTION__H
#define STATE__STATEFIGHTACTION__H


namespace state {

  enum StateFightAction {
    IDLE     = 1,
    MOVING     = 2,
    ATTACKING     = 3
  };

};

#endif
