// Generated by dia2code
#ifndef STATE__TYPEID__H
#define STATE__TYPEID__H


namespace state {

  enum TypeID {
    PLAYER     = 0,
    SKELETON     = 1,
    BOWMAN     = 2,
    SORCERER     = 3
  };

};

#endif
