// Generated by dia2code
#ifndef STATE__WANDER__H
#define STATE__WANDER__H


namespace state {
  class State;
}

#include "StateWanderAction.h"
#include "State.h"

namespace state {

  /// class Wander - On peut ajouter un attribut wandering de type bool qui va nous permettre de quitter le mode Wander, même s'il existe déjà le LAUNCHING = 3 de StateWanderAction
  class Wander : public state::State {
    // Associations
    // Operations
  public:
    int getWanderAction (StateWanderAction state);
    // Setters and Getters
  };

};

#endif
