// Generated by dia2code
#ifndef RENDER__STATELAYER__H
#define RENDER__STATELAYER__H

#include <SFML/Graphics.hpp>
#include <vector>
#include <memory>
#include <string>

namespace state {
  class State;
};
namespace render {
  class Tile;
  class LoadLayer;
}

#include "state/State.h"
#include "Tile.h"
#include "LoadLayer.h"

namespace render {

  /// class StateLayer - 
  class StateLayer {
    // Associations
    // Attributes
  public:
    sf::Font font;
    sf::RenderWindow& window;
    std::vector<std::unique_ptr<LoadLayer>> layer;
    // Operations
  public:
    void initLayer (state::State& state);
    StateLayer (state::State& state, sf::RenderWindow& window, std::string env);
    std::vector<std::unique_ptr<Tile>>& getTile ();
    std::vector<std::unique_ptr<LoadLayer>>& getLayer ();
    void stateChanged (const state::State e, state::State& state);
    void draw (sf::RenderWindow& window);
    bool showText ();
    // Setters and Getters
  };

};

#endif
