// Generated by dia2code
#ifndef RENDER__TILE__H
#define RENDER__TILE__H

#include <string>
#include <SFML/Graphics.hpp>

namespace sf {
  class Texture;
}

#include "TileID.h"

namespace render {

  /// class Tile - 
  class Tile {
    // Associations
    // Attributes
  public:
    TileID id;
    /// 			
    std::string resourceFile;
    sf::Texture textureTileset;
    int cellWidth;
    int cellHeight;
    // Operations
  public:
    Tile (TileID newID);
    const std::string getImageFile ();
    int const getCellWidth ();
    int const getCellHeight ();
    int const getTileID ();
    sf::Texture& getTexture ();
    // Setters and Getters
  };

};

#endif
