// Generated by dia2code
#ifndef RENDER__TILEID__H
#define RENDER__TILEID__H


namespace render {

  enum TileID {
    CHARACTER     = 1,
    HUD     = 2,
    CURSOR     = 3,
    MAPCELL     = 4
  };

};

#endif
